//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteWideSearch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteWideSearch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteWideSearch", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results &lt;span class=&apos;results-range&apos;&gt;{0}&amp;ndash;{1}&lt;/span&gt; of &lt;span class=&apos;results-num&apos;&gt;{2}&lt;/span&gt;..
        /// </summary>
        internal static string bottomResultsXofYFormatter {
            get {
                return ResourceManager.GetString("bottomResultsXofYFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you mean.
        /// </summary>
        internal static string DidYouMeanText {
            get {
                return ResourceManager.GetString("DidYouMeanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a search phrase..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/search_site.gif.
        /// </summary>
        internal static string imageURL {
            get {
                return ResourceManager.GetString("imageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next&amp;nbsp;&amp;gt;.
        /// </summary>
        internal static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string PageUnit {
            get {
                return ResourceManager.GetString("PageUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results per page..
        /// </summary>
        internal static string PageUnitResults {
            get {
                return ResourceManager.GetString("PageUnitResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;&amp;nbsp;Previous.
        /// </summary>
        internal static string PrevPageText {
            get {
                return ResourceManager.GetString("PrevPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} results found for: .
        /// </summary>
        internal static string ResultsFor {
            get {
                return ResourceManager.GetString("ResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for:.
        /// </summary>
        internal static string ResultsForText {
            get {
                return ResourceManager.GetString("ResultsForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Search&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;.
        /// </summary>
        internal static string SearchTypeText1 {
            get {
                return ResourceManager.GetString("SearchTypeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Within Results.
        /// </summary>
        internal static string SearchTypeText2 {
            get {
                return ResourceManager.GetString("SearchTypeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string TextChangePageUnit {
            get {
                return ResourceManager.GetString("TextChangePageUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results - National Cancer Institute.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results &lt;span class=&apos;results-range&apos;&gt;{0}&amp;ndash;{1}&lt;/span&gt; of &lt;span class=&apos;results-num&apos;&gt;{2}&lt;/span&gt; for:.
        /// </summary>
        internal static string topResultsXofYFormatter {
            get {
                return ResourceManager.GetString("topResultsXofYFormatter", resourceCulture);
            }
        }
    }
}
