using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using NCI.Logging;
using NCI.Services.Dictionary.BusinessObjects;

namespace NCI.Services.Dictionary
{
    /// <summary>
    /// Infrastructure for the dictionary service.
    /// Implments the business logic of retrieving dictionary data.
    /// </summary>
    internal class DictionaryManager
    {
        static Log log = new Log(typeof(DictionaryManager));

        // These values should come from the GateKeeper backend processing.
        const String AUDIENCE_PATIENT = "Patient";
        const String AUDIENCE_HEALTHPROF = "Health Professional";


        #region Hard-coded returns for initial stub-out

        private String[] CancerTermEnglish = new String[] {
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12345"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cancer Term""},",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12346"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cancer Term 2""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12347"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cancer Term 3""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12348"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cancer Term 4""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12349"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cancer Term 5""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12350"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cancer Term 6""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12351"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cancer Term 7""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12352"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cancer Term 8""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12353"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cancer Term 9""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12354"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cancer Term 10""}"
        };

        private String[] CancerTermSpanish = new String[] {
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12345"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""""},""related"":{""drug_summary"":[],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cáncer término (en español)""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12346"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""""},""related"":{""drug_summary"":[],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cáncer término 2 (en español)""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12347"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""""},""related"":{""drug_summary"":[],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cáncer término 3 (en español)""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12348"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""""},""related"":{""drug_summary"":[],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cáncer término 4 (en español)""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12349"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""""},""related"":{""drug_summary"":[],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cáncer término 5 (en español)""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12350"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""""},""related"":{""drug_summary"":[],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cáncer término 6 (en español)""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12351"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""""},""related"":{""drug_summary"":[],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cáncer término 7 (en español)""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12352"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""""},""related"":{""drug_summary"":[],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cáncer término 8 (en español)""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12353"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""""},""related"":{""drug_summary"":[],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cáncer término 9 (en español)""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12354"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""""},""related"":{""drug_summary"":[],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Cáncer término 10 (en español)""}"
        };

        private String[] GeneticTermEnglish = new String[]{
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12345"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Genetic Term""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12346"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Genetic Term 2""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12347"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Genetic Term 3""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12348"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Genetic Term 4""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12349"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Genetic Term 5""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12350"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Genetic Term 6""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12351"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Genetic Term 7""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12352"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Genetic Term 8""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12353"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Genetic Term 9""}",
            @"{""alias"":[],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12354"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":{""drug_summary"":[{""id"":45693,""text"":""Related Drug Summary""}],""external"":[{""text"":""Great Googly Moogly!"",""url"":""http:\/\/www.google.com\/""}],""summary"":[{""id"":62956,""text"":""A Summary""}],""term"":[{""dictionary"":""Term"",""id"":""12345"",""text"":""A related Term""}]},""term"":""Genetic Term 10""}"
        };

        private String[] DrugTermEnglish = new String[] {
            @"{""alias"":[{""name"":""Alias 1"",""type"":""US brand name""},{""name"":""Alias 2"",""type"":""Abbreviation""},{""name"":""Alias 3"",""type"":""IND code""},{""name"":""Alias 4"",""type"":""NSC number""},{""name"":""Alias 5"",""type"":""Synonym""},{""name"":""Alias 6"",""type"":""Synonym""},{""name"":""Alias 7"",""type"":""Synonym""},{""name"":""Alias 8"",""type"":""Synonym""},{""name"":""Alias 9"",""type"":""Synonym""},{""name"":""Alias 10"",""type"":""Synonym""}],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12345"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":null,""term"":""Drug Term""}",
            @"{""alias"":[{""name"":""Alias 1"",""type"":""US brand name""},{""name"":""Alias 2"",""type"":""Abbreviation""},{""name"":""Alias 3"",""type"":""IND code""},{""name"":""Alias 4"",""type"":""NSC number""},{""name"":""Alias 5"",""type"":""Synonym""},{""name"":""Alias 6"",""type"":""Synonym""},{""name"":""Alias 7"",""type"":""Synonym""},{""name"":""Alias 8"",""type"":""Synonym""},{""name"":""Alias 9"",""type"":""Synonym""},{""name"":""Alias 10"",""type"":""Synonym""}],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12346"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":null,""term"":""Drug Term 2""}",
            @"{""alias"":[{""name"":""Alias 1"",""type"":""US brand name""},{""name"":""Alias 2"",""type"":""Abbreviation""},{""name"":""Alias 3"",""type"":""IND code""},{""name"":""Alias 4"",""type"":""NSC number""},{""name"":""Alias 5"",""type"":""Synonym""},{""name"":""Alias 6"",""type"":""Synonym""},{""name"":""Alias 7"",""type"":""Synonym""},{""name"":""Alias 8"",""type"":""Synonym""},{""name"":""Alias 9"",""type"":""Synonym""},{""name"":""Alias 10"",""type"":""Synonym""}],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12347"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":null,""term"":""Drug Term 3""}",
            @"{""alias"":[{""name"":""Alias 1"",""type"":""US brand name""},{""name"":""Alias 2"",""type"":""Abbreviation""},{""name"":""Alias 3"",""type"":""IND code""},{""name"":""Alias 4"",""type"":""NSC number""},{""name"":""Alias 5"",""type"":""Synonym""},{""name"":""Alias 6"",""type"":""Synonym""},{""name"":""Alias 7"",""type"":""Synonym""},{""name"":""Alias 8"",""type"":""Synonym""},{""name"":""Alias 9"",""type"":""Synonym""},{""name"":""Alias 10"",""type"":""Synonym""}],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12348"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":null,""term"":""Drug Term 4""}",
            @"{""alias"":[{""name"":""Alias 1"",""type"":""US brand name""},{""name"":""Alias 2"",""type"":""Abbreviation""},{""name"":""Alias 3"",""type"":""IND code""},{""name"":""Alias 4"",""type"":""NSC number""},{""name"":""Alias 5"",""type"":""Synonym""},{""name"":""Alias 6"",""type"":""Synonym""},{""name"":""Alias 7"",""type"":""Synonym""},{""name"":""Alias 8"",""type"":""Synonym""},{""name"":""Alias 9"",""type"":""Synonym""},{""name"":""Alias 10"",""type"":""Synonym""}],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12349"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":null,""term"":""Drug Term 5""}",
            @"{""alias"":[{""name"":""Alias 1"",""type"":""US brand name""},{""name"":""Alias 2"",""type"":""Abbreviation""},{""name"":""Alias 3"",""type"":""IND code""},{""name"":""Alias 4"",""type"":""NSC number""},{""name"":""Alias 5"",""type"":""Synonym""},{""name"":""Alias 6"",""type"":""Synonym""},{""name"":""Alias 7"",""type"":""Synonym""},{""name"":""Alias 8"",""type"":""Synonym""},{""name"":""Alias 9"",""type"":""Synonym""},{""name"":""Alias 10"",""type"":""Synonym""}],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12350"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":null,""term"":""Drug Term 6""}",
            @"{""alias"":[{""name"":""Alias 1"",""type"":""US brand name""},{""name"":""Alias 2"",""type"":""Abbreviation""},{""name"":""Alias 3"",""type"":""IND code""},{""name"":""Alias 4"",""type"":""NSC number""},{""name"":""Alias 5"",""type"":""Synonym""},{""name"":""Alias 6"",""type"":""Synonym""},{""name"":""Alias 7"",""type"":""Synonym""},{""name"":""Alias 8"",""type"":""Synonym""},{""name"":""Alias 9"",""type"":""Synonym""},{""name"":""Alias 10"",""type"":""Synonym""}],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12351"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":null,""term"":""Drug Term 7""}",
            @"{""alias"":[{""name"":""Alias 1"",""type"":""US brand name""},{""name"":""Alias 2"",""type"":""Abbreviation""},{""name"":""Alias 3"",""type"":""IND code""},{""name"":""Alias 4"",""type"":""NSC number""},{""name"":""Alias 5"",""type"":""Synonym""},{""name"":""Alias 6"",""type"":""Synonym""},{""name"":""Alias 7"",""type"":""Synonym""},{""name"":""Alias 8"",""type"":""Synonym""},{""name"":""Alias 9"",""type"":""Synonym""},{""name"":""Alias 10"",""type"":""Synonym""}],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12352"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":null,""term"":""Drug Term 8""}",
            @"{""alias"":[{""name"":""Alias 1"",""type"":""US brand name""},{""name"":""Alias 2"",""type"":""Abbreviation""},{""name"":""Alias 3"",""type"":""IND code""},{""name"":""Alias 4"",""type"":""NSC number""},{""name"":""Alias 5"",""type"":""Synonym""},{""name"":""Alias 6"",""type"":""Synonym""},{""name"":""Alias 7"",""type"":""Synonym""},{""name"":""Alias 8"",""type"":""Synonym""},{""name"":""Alias 9"",""type"":""Synonym""},{""name"":""Alias 10"",""type"":""Synonym""}],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12353"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":null,""term"":""Drug Term 9""}",
            @"{""alias"":[{""name"":""Alias 1"",""type"":""US brand name""},{""name"":""Alias 2"",""type"":""Abbreviation""},{""name"":""Alias 3"",""type"":""IND code""},{""name"":""Alias 4"",""type"":""NSC number""},{""name"":""Alias 5"",""type"":""Synonym""},{""name"":""Alias 6"",""type"":""Synonym""},{""name"":""Alias 7"",""type"":""Synonym""},{""name"":""Alias 8"",""type"":""Synonym""},{""name"":""Alias 9"",""type"":""Synonym""},{""name"":""Alias 10"",""type"":""Synonym""}],""date_first_published"":""01-01-0001"",""date_last_modified"":""12-31-9999"",""definition"":{""html"":""<p>Term Definition in HTML<\/p>"",""text"":""Term Definition""},""id"":""12354"",""images"":[{""alt"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""caption"":""Computed tomography (CT) scan of the abdomen. The patient lies on a table that slides through the CT machine, which takes x-ray pictures of the inside of the body."",""filename"":""CDR428405-750.jpg""},{""alt"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film."",""caption"":""Bone scan. A small amount of radioactive material is injected into the patient's bloodstream and collects in abnormal cells in the bones. As the patient lies on a table that slides under the scanner, the radioactive material is detected and images are made on a computer screen or film.."",""filename"":""CDR466541-750.jpg""}],""pronunciation"":{""audio"":""http:\/\/www.cancer.gov\/PublishedContent\/Media\/CDR\/media\/705333.mp3"",""key"":""KAN-ser""},""related"":null,""term"":""Drug Term 10""}"
        };

        #endregion


        /// <summary>
        /// Retrieves a single dictionary term based on its specific Term ID.
        /// </summary>
        /// <param name="termId">The ID of the Term to be retrieved</param>
        /// <param name="dictionary">The dictionary to retreive the Term from.
        ///     Valid values are
        ///        Term - Dictionary of Cancer Terms
        ///        drug - Drug Dictionary
        ///        genetic - Dictionary of Genetics Terms
        /// </param>
        /// <param name="language">The Term's desired language.
        ///     Supported values are:
        ///         en - English
        ///         es - Spanish
        /// </param>
        /// <param name="version">String identifying which vereion of the API to match.</param>
        /// <returns>A data structure containing both meta data about the request and a string containing a JSON representation
        /// of the particular definition identified by the inputs to the method.
        /// </returns>
        public TermReturn GetTerm(int termId, DictionaryType dictionary, Language language, String version)
        {
            log.debug(string.Format("Enter GetTerm( {0}, {1}, {2}).", termId, dictionary, language, version));

            #region Argument Validation

            if (termId <= 0)
            {
                string msg = string.Format("termId - expected a positive value, found '{0}'.", termId);
                log.error(msg);
                throw new ArgumentException(msg);
            }

            if (!Enum.IsDefined(typeof(DictionaryType), dictionary) || dictionary == DictionaryType.Unknown)
            {
                string msg = string.Format("dictionary contains invalid value '{0}'.", dictionary);
                log.error(msg);
                throw new ArgumentException(msg);
            }

            if (!Enum.IsDefined(typeof(Language), language) || language == Language.Unknown)
            {
                string msg = string.Format("language contains invalid value '{0}'.", language);
                log.error(msg);
                throw new ArgumentException(msg);
            }

            if (string.IsNullOrEmpty(version))
            {
                log.error("version is null or empty.");
                throw new ArgumentException("version is null or empty.");
            }

            #endregion

            // In the initial implementation, the audience is implied by the particular dictionary being used.
            AudienceType audience = GetAudienceFromDictionaryType(dictionary);

            DictionaryQuery query = new DictionaryQuery();
            DataTable dtTerm = query.GetTerm(termId, dictionary, language, audience, version);

            List<String> messages = new List<string>();

            String term = string.Empty;

            // Normal, found 1 match.
            int resultCount = dtTerm.Rows.Count;
            if (resultCount == 1)
            {
                log.debug("Found 1 result.");
                messages.Add("OK");
                term = dtTerm.Rows[0].Field<string>("object");
            }
            // "Normal", found no matches.
            else if (resultCount == 0)
            {
                log.debug("Found 0 results.");
                messages.Add("No result found.");
                term = string.Empty;
            }
            // "Odd" case. With multiple matches, return the first one.
            else // result count must be greater than 1
            {
                log.warning(string.Format("Expected to find one result for term {0}, found {1} instead.", termId, resultCount));
                messages.Add("OK");
                term = dtTerm.Rows[0].Field<string>("object");
            }


            // Build up the return data structure.
            TermReturn trmReturn = new TermReturn();

            TermReturnMeta meta = new TermReturnMeta();
            meta.Language = language.ToString();
            meta.Audience = audience.ToString();
            meta.Messages = messages.ToArray();

            trmReturn.Meta = meta;
            trmReturn.Term = term;

            return trmReturn;
        }

        /// <summary>
        /// Performs a search for terms with names matching searchText.
        /// </summary>
        /// <param name="searchText">text to search for.</param>
        /// <param name="searchType">The type of search to perform.
        ///     Valid values are:
        ///         Begins - Search for terms beginning with searchText.
        ///         Contains - Search for terms containing searchText.
        ///         Magic - Search for terms beginning with searchText, followed by those containing searchText.
        /// </param>
        /// <param name="offset">Offset into the list of matches for the first result to return.</param>
        /// <param name="maxResults">The maximum number of results to return. Must be at least 10.</param>
        /// <param name="dictionary">The dictionary to retreive the Term from.
        ///     Valid values are
        ///        Term - Dictionary of Cancer Terms
        ///        drug - Drug Dictionary
        ///        genetic - Dictionary of Genetics Terms
        /// </param>
        /// <param name="language">The Term's desired language.
        ///     Supported values are:
        ///         en - English
        ///         es - Spanish
        /// </param>
        /// <param name="version">String identifying which vereion of the API to match.</param>
        /// <returns></returns>
        public SearchReturn Search(String searchText, SearchType searchType, int offset, int maxResults, DictionaryType dictionary, Language language, String version)
        {
            log.debug(string.Format("Enter Search( {0}, {1}, {2}, {3}, {4}, {5}, {6}).", searchText, searchType, offset, maxResults, dictionary, language, version));

            // Sanity check for the offset and maxResults
            if (offset < 0) offset = 0;
            if (maxResults < 10) maxResults = 10;


            // In the initial implementation, the audience is implied by the particular dictionary being used.
            AudienceType audience = GetAudienceFromDictionaryType(dictionary);

            DictionaryQuery query = new DictionaryQuery();
            SearchResults results = query.Search(searchText, searchType, offset, maxResults, dictionary, language, audience, version);

            List<String> messages = new List<string>();

            int resultCount = results.MatchCount;

            // Report the count in a human-readable format.
            String message = String.Format("Found {0} results.", resultCount);
            log.debug(message);
            messages.Add(message);

            // Retrieve results
            List<String> foundTerms = new List<string>();
            foreach (DataRow row in results.Data.Rows)
                foundTerms.Add(row.Field<string>("object"));

            // Populate return metadata structure
            SearchReturnMeta meta = new SearchReturnMeta();
            meta.Language = language.ToString();
            meta.Audience = audience.ToString();
            meta.Offset = offset;
            meta.ResultCount = resultCount;
            meta.Messages = messages.ToArray();


            // Combine meta and results to create the final return object.
            SearchReturn srchReturn = new SearchReturn()
            {
                Result = foundTerms.ToArray(),
                Meta = meta
            };

            return srchReturn;
        }

        public SuggestReturn SearchSuggest(String searchText, SearchType searchType, DictionaryType dictionary, Language language, String version)
        {
            log.debug(string.Format("Enter SearchSuggest( {0}, {1}, {2}, {3}, {4}).", searchText, searchType, dictionary, language, version));

            SuggestReturn srchReturn;

            DictionarySuggestion[] results = new DictionarySuggestion[] { };

            SuggestReturnMeta meta = new SuggestReturnMeta();

            switch (dictionary)
            {
                case DictionaryType.term:
                    if (language == Language.English)
                    {
                        results = new DictionarySuggestion[] {
                            new DictionarySuggestion(){ ID = "1", Term = "Cancer Term 1" },
                            new DictionarySuggestion(){ ID = "2", Term = "Cancer Term 2" },
                            new DictionarySuggestion(){ ID = "3", Term = "Cancer Term 3" },
                            new DictionarySuggestion(){ ID = "4", Term = "Cancer Term 4" },
                            new DictionarySuggestion(){ ID = "5", Term = "Cancer Term 5" },
                            new DictionarySuggestion(){ ID = "6", Term = "Cancer Term 6" },
                            new DictionarySuggestion(){ ID = "7", Term = "Cancer Term 7" },
                            new DictionarySuggestion(){ ID = "8", Term = "Cancer Term 8" },
                            new DictionarySuggestion(){ ID = "9", Term = "Cancer Term 9" },
                            new DictionarySuggestion(){ ID = "10", Term = "Cancer Term 10" }
                        };
                        meta.Messages = new string[] { "OK" };
                    }
                    else if (language == Language.Spanish)
                    {
                        results = new DictionarySuggestion[] {
                            new DictionarySuggestion(){ ID = "1", Term = "Spanish Cancer Term 1" },
                            new DictionarySuggestion(){ ID = "2", Term = "Spanish Cancer Term 2" },
                            new DictionarySuggestion(){ ID = "3", Term = "Spanish Cancer Term 3" },
                            new DictionarySuggestion(){ ID = "4", Term = "Spanish Cancer Term 4" },
                            new DictionarySuggestion(){ ID = "5", Term = "Spanish Cancer Term 5" },
                            new DictionarySuggestion(){ ID = "6", Term = "Spanish Cancer Term 6" },
                            new DictionarySuggestion(){ ID = "7", Term = "Spanish Cancer Term 7" },
                            new DictionarySuggestion(){ ID = "8", Term = "Spanish Cancer Term 8" },
                            new DictionarySuggestion(){ ID = "9", Term =  "Spanish Cancer Term 9" },
                            new DictionarySuggestion(){ ID = "10", Term = "Spanish Cancer Term 10" }
                        };
                        meta.Messages = new string[] { "OK" };
                    }
                    else
                    {
                        throw new UnsupportedLanguageException(language, dictionary);
                    }
                    break;
                case DictionaryType.drug:
                    if (language == Language.English)
                    {
                        results = new DictionarySuggestion[] {
                            new DictionarySuggestion(){ ID = "1", Term =  "Drug Term 1" },
                            new DictionarySuggestion(){ ID = "2", Term =  "Drug Term 2" },
                            new DictionarySuggestion(){ ID = "3", Term =  "Drug Term 3" },
                            new DictionarySuggestion(){ ID = "4", Term =  "Drug Term 4" },
                            new DictionarySuggestion(){ ID = "5", Term =  "Drug Term 5" },
                            new DictionarySuggestion(){ ID = "6", Term =  "Drug Term 6" },
                            new DictionarySuggestion(){ ID = "7", Term =  "Drug Term 7" },
                            new DictionarySuggestion(){ ID = "8", Term =  "Drug Term 8" },
                            new DictionarySuggestion(){ ID = "9", Term =  "Drug Term 9" },
                            new DictionarySuggestion(){ ID = "10", Term = "Drug Term 10" }
                        };
                        meta.Messages = new string[] { "OK" };
                    }
                    else
                    {
                        throw new UnsupportedLanguageException(language, dictionary);
                    }
                    break;
                case DictionaryType.genetic:
                    if (language == Language.English)
                    {
                        results = new DictionarySuggestion[] {
                            new DictionarySuggestion(){ ID = "1", Term =  "Genetic Term 1" },
                            new DictionarySuggestion(){ ID = "2", Term =  "Genetic Term 2" },
                            new DictionarySuggestion(){ ID = "3", Term =  "Genetic Term 3" },
                            new DictionarySuggestion(){ ID = "4", Term =  "Genetic Term 4" },
                            new DictionarySuggestion(){ ID = "5", Term =  "Genetic Term 5" },
                            new DictionarySuggestion(){ ID = "6", Term =  "Genetic Term 6" },
                            new DictionarySuggestion(){ ID = "7", Term =  "Genetic Term 7" },
                            new DictionarySuggestion(){ ID = "8", Term =  "Genetic Term 8" },
                            new DictionarySuggestion(){ ID = "9", Term =  "Genetic Term 9" },
                            new DictionarySuggestion(){ ID = "10", Term = "Genetic Term 10" }
                        };
                        meta.Messages = new string[] { "OK" };
                    }
                    else
                    {
                        throw new UnsupportedLanguageException(language, dictionary);
                    }
                    break;
                default:
                    throw new DictionaryValidationException(string.Format("Unknown dictionary type '{0}'.", dictionary));
            }

            meta.ResultCount = results.Length;


            srchReturn = new SuggestReturn()
            {
                Result = results,
                Meta = meta
            };

            return srchReturn;

        }

        private AudienceType GetAudienceFromDictionaryType(DictionaryType dictionary)
        {
            AudienceType audience;

            switch (dictionary)
            {
                case DictionaryType.term:
                    audience = AudienceType.Patient;
                    break;
                case DictionaryType.drug:
                    audience = AudienceType.HealthProfessional;
                    break;
                case DictionaryType.genetic:
                    audience = AudienceType.HealthProfessional;
                    break;

                case DictionaryType.Unknown:
                default:
                    {
                        string msg = string.Format("Unspported dictionary type '{0}'.", dictionary);
                        log.error(msg);
                        throw new ArgumentException(msg);
                    }
            }

            return audience;
        }
    }
}
