//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCI.Search.BestBets.Lucene {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BestBetsWordForms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BestBetsWordForms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCI.Search.BestBets.Lucene.BestBetsWordForms", typeof(BestBetsWordForms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstracts.
        /// </summary>
        internal static string _abstract {
            get {
                return ResourceManager.GetString("abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bases.
        /// </summary>
        internal static string _base {
            get {
                return ResourceManager.GetString("base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catches.
        /// </summary>
        internal static string _catch {
            get {
                return ResourceManager.GetString("catch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decimals.
        /// </summary>
        internal static string _decimal {
            get {
                return ResourceManager.GetString("decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delegates.
        /// </summary>
        internal static string _delegate {
            get {
                return ResourceManager.GetString("delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doubles.
        /// </summary>
        internal static string _double {
            get {
                return ResourceManager.GetString("double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to floats.
        /// </summary>
        internal static string _float {
            get {
                return ResourceManager.GetString("float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nulls.
        /// </summary>
        internal static string _null {
            get {
                return ResourceManager.GetString("null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objects.
        /// </summary>
        internal static string _object {
            get {
                return ResourceManager.GetString("object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operators.
        /// </summary>
        internal static string _operator {
            get {
                return ResourceManager.GetString("operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privates.
        /// </summary>
        internal static string _private {
            get {
                return ResourceManager.GetString("private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strings.
        /// </summary>
        internal static string _string {
            get {
                return ResourceManager.GetString("string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to throws.
        /// </summary>
        internal static string _throw {
            get {
                return ResourceManager.GetString("throw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tries.
        /// </summary>
        internal static string _try {
            get {
                return ResourceManager.GetString("try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voids.
        /// </summary>
        internal static string _void {
            get {
                return ResourceManager.GetString("void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volatiles.
        /// </summary>
        internal static string _volatile {
            get {
                return ResourceManager.GetString("volatile", resourceCulture);
            }
        }
        
        

    }
}
